### ISSUE TITLE
FilterError due to missing less in dev env

### ISSUE THREAD

**Issue by codersquid** [PyCon/pycon#255]
Feel free to assign this to me. I'm opening it so that I don't forget to make a pull request with documentation improvements once I figure this out.

The docs are missing the step of installing the less module, and I found [a nice blog post](calvinx.com/2013/07/11/python-virtualenv-with-node-environment-via-nodeenv/) on setting up a virtualenv equivalent for node.js and used that.

However, I am probably still missing a step and/or have a wrong setting.

btw, ./build-css.sh fails due to a missing site.css.

```
Template error:
In template /home/pycon/site/pycon/pycon/templates/responsive_base.html, error at line 15
   
module.js:340
    throw err;
          ^
Error: Cannot find module 'less'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/bin/lessc:9:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```
full traceback and local.py https://gist.github.com/codersquid/7874019

**Comment by brandon-rhodes** [comment]
Happily, my new Ansible playbook that gets invoked by `vagrant provision` now features its own automatic steps for making sure that Node, npm, and Less all get installed, so individual developers no longer need to worry about doing it by hand. Sorry, @codersquid, that you had to spend your own time doing the installation by hand!
