### ISSUE TITLE
500 downloading zipped sponsor logos

### ISSUE THREAD

**Issue by dpoirier** [PyCon/pycon#436]
E.g. go to https://staging-pycon.python.org/2016/sponsors/ziplogos/ or https://pycon-prod.iad1.psf.io/2016/sponsors/ziplogos/, get a 500.  From the error email:

Traceback (most recent call last):

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 151, in get_response
    response = callback(request, **param_dict)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 91, in _wrapped_view
    response = view_func(request, *args, **kwargs)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/views/defaults.py", line 26, in page_not_found
    return http.HttpResponseNotFound(template.render(RequestContext(request, {'request_path': request.path})))

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 124, in render
    return compiled_parent._render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 63, in render
    result = block.nodelist.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/templatetags/cache.py", line 34, in render
    value = self.nodelist.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 830, in render
    bit = self.render_node(node, context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render_node
    return node.render(context)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 196, in render
    nodelist.append(node.render(context))

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 284, in render
    if match:

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 157, in __nonzero__
    return type(self).__bool__(self)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 151, in __bool__
    next(iter(self))

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 139, in _result_iter
    self._fill_cache()

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 941, in _fill_cache
    self._result_cache.append(next(self._iter))

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 317, in iterator
    for row in compiler.results_iter():

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 775, in results_iter
    for rows in self.execute_sql(MULTI):

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 846, in execute_sql
    cursor.execute(sql, params)

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 58, in execute
    six.reraise(utils.DatabaseError, utils.DatabaseError(*tuple(e.args)), sys.exc_info()[2])

  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 54, in execute
    return self.cursor.execute(query, args)

DatabaseError: column sponsorship_sponsor.contact_email does not exist
LINE 1: ...nnotation", "sponsorship_sponsor"."contact_name", "sponsorsh...
                                                             ^

**Comment by dpoirier** [comment]
After that error was fixed, a new one turned up.  It looks like moving the web logo from a benefit record to the main sponsorship record has broken the sponsor logo download:

Internal Server Error: /2016/sponsors/ziplogos/
Traceback (most recent call last):
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/srv/pycon/pycon/pycon/sponsorship/views.py", line 143, in sponsor_zip_logo_files
    benefit = Benefit.objects.get(name=benefit_name)
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 357, in get
    self.model._meta.object_name)
DoesNotExist: Benefit matching query does not exist.
