### ISSUE TITLE
Error deleting all sponsors

### ISSUE THREAD

**Issue by dpoirier** [PyCon/pycon#509]
Internal Server Error: /2016/admin/sponsorship/sponsor/
Traceback (most recent call last):
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 34, in _wrapper
    return bound_func(*args, **kwargs)
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/utils/decorators.py", line 30, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1574, in changelist_view
    response = self.response_action(request, queryset=cl.get_queryset(request))
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1333, in response_action
    response = func(self, request, queryset)
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/contrib/admin/actions.py", line 37, in delete_selected
    queryset, opts, request.user, modeladmin.admin_site, using)
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 153, in get_deleted_objects
    to_delete = collector.nested(format_callback)
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 213, in nested
    roots.extend(self._nested(root, seen, format_callback))
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 196, in _nested
    children.extend(self._nested(child, seen, format_callback))
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 198, in _nested
    ret = [format_callback(obj)]
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 126, in format_callback
    force_text(obj))
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/utils/encoding.py", line 92, in force_text
    s = six.text_type(s)
  File "/srv/pycon/pycon/pycon/sponsorship/models.py", line 372, in __unicode__
    return u"%s - %s (%s)" % (self.sponsor, self.benefit,
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/fields/related.py", line 610, in __get__
    rel_obj = qs.get()
  File "/srv/pycon/env/local/lib/python2.7/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
DoesNotExist: Benefit matching query does not exist.

**Comment by dpoirier** [comment]
That turned out to be a problem in the data; somehow the benefit records we are not using anymore were deleted but not other records that still had foreign keys to them.

I've fixed it up and you should be able to delete the sponsors now.
